### ISSUE TITLE
Update available prompts break structured output, being dumped to stdout

### ISSUE THREAD

**Issue by webknjaz** [ninxsoft/mist-cli#180]
### :beetle: Description

I have Ansible-based automation that calls `mist list installer '15.3' --latest  --compatible --no-ansi --quiet --output-type=yaml` and feeds the result into a YAML parser, which then explodes on corrupted data.

This is because 
```yaml
┌──────────────────┐
│ UPDATE AVAILABLE │
└──────────────────┘
  ├─ \u001b[0;0mThere is a mist update available (current version: 2.1, latest version: 2.1.1)\u001b[0;0m
  ├─ \u001b[0;0mVisit https://github.com/ninxsoft/mist-cli to grab the latest release of mist\u001b[0;0m
- build: 24D60
  compatible: true
  date: '2025-01-27'
  identifier: 072-08251
  name: macOS Sequoia
  size: 15253153260
  version: '15.3'
```
is not a valid YAML document. This also shows that `--no-ansi` doesn't work (#120 missed this?), which is secondary for my case.

### :clipboard: Steps to Reproduce

See above.

### :white_check_mark: Expected Behaviour

stdout must only contain structured output (YAML in this case). Any hints, warnings, recommendations, explanations must go into stderr.

### :computer: Environment

- mist version (`mist --version`): 2.1
- macOS Version (`sw_vers`): irrelevant
- Hardware (`system_profiler SPHardwareDataType`): irrelevant

### :camera: Screenshots

N/A

### :information_source: Additional context

N/A
